Added Hmine algorithm
rasbt/mlxtend pull request #1020
Opened 2023-03-23 11:37 UTC by fatihsen20

### Code of Conduct
New feature.

### Description

In order to enrich the library and to compare the speed and memory costs of certain algorithms, I added the hmine algorithm to the library.
### Related issues or pull requests
None

### Pull Request Checklist

- [ ] Added a note about the modification or contribution to the `./docs/sources/CHANGELOG.md` file (if applicable)
- [ ] Added appropriate unit test functions in the `./mlxtend/*/tests` directories (if applicable)
- [ ] Modify documentation in the corresponding Jupyter Notebook under `mlxtend/docs/sources/` (if applicable)
- [ ] Ran `PYTHONPATH='.' pytest ./mlxtend -sv` and make sure that all unit tests pass (for small modifications, it might be sufficient to only run the specific test file, e.g., `PYTHONPATH='.' pytest ./mlxtend/classifier/tests/test_stacking_cv_classifier.py -sv`)
- [ ] Checked for style issues by running `flake8 ./mlxtend`

2023-03-23 15:33 UTC, rasbt requested changes
Awesome, thanks so much for the contribution! 

H-Mine is guaranteed to find the same frequent itemsets as apriori and fp-growth, correct? Would it be possible to add a unit test to test for equivalence with the existing algos?

2023-03-23 15:33 UTC, rasbt commented on docs/sources/CHANGELOG.md
>  ### Version 0.1.1 (2014-08-13)
I think you accidentally added this to the wrong version in the Changelog

2023-03-23 15:34 UTC, rasbt commented
PS: Don't worry about the linter above, we can address that (happy to take care of that) at the very end.

2023-03-24 21:54 UTC, rasbt commented
Thanks a lot for the update! I will do my best to review it this weekend!

2023-03-25 10:38 UTC, fatihsen20 commented
I always overlook the isort rules. I am sorry 🥲

2023-03-25 17:30 UTC, rasbt commented
No worries about that! The style checks are really not a big deal, we can address those at the very end upon merging.

2023-03-25 17:42 UTC, rasbt approved these changes

2023-03-27 09:32 UTC, fatihsen20 commented
Hello, will my pull request be merge? I am very excited about this 😊 @rasbt

2023-03-27 15:46 UTC, rasbt commented
This is a fantastic PR! And sorry, will merge soon! Haven't had a chance to go over the docs yet! I have a question here: 
<img width="965" alt="Screenshot 2023-03-27 at 10 44 12 AM" src="https://user-images.githubusercontent.com/5618407/227993022-54a72b34-d5d1-4955-b13a-5e77761aa331.png">

You mentioned

> on a large dataset.

but did you mean 

> on a small dataset.

I.e., the dataset from the example above? No worries about fixing it. I did some other tweaks in the docs and will update soon (pls don't modify the Nb in the meantime due to merge conflicts, Jupyter NB's are still a bit tricky on GitHub 😅)

2023-03-27 17:09 UTC, fatihsen20 commented
> This is a fantastic PR! And sorry, will merge soon! Haven't had a chance to go over the docs yet! I have a question here: <img alt="Screenshot 2023-03-27 at 10 44 12 AM" width="965" src="https://user-images.githubusercontent.com/5618407/227993022-54a72b34-d5d1-4955-b13a-5e77761aa331.png">
> 
> You mentioned
> 
> > on a large dataset.
> 
> but did you mean
> 
> > on a small dataset.
> 
> I.e., the dataset from the example above? No worries about fixing it. I did some other tweaks in the docs and will update soon (pls don't modify the Nb in the meantime due to merge conflicts, Jupyter NB's are still a bit tricky on GitHub 😅)

Sorry, I probably missed it while preparing the document. Yes, there will be a small dataset in the example there. Thank you so much for your hard work 😊

2023-03-27 17:11 UTC, rasbt commented
Oh I thought it was based on the small example at the top. So you ran the benchmark on a small hands-on dataset if I understand it correctly? I think we can leave things as is unless it's not too large and we can add it to the doc repo. What do you think?

2023-03-27 17:23 UTC, fatihsen20 commented
> Oh I thought it was based on the small example at the top. So you ran the benchmark on a small hands-on dataset if I understand it correctly? I think we can leave things as is unless it's not too large and we can add it to the doc repo. What do you think?

Yes it was based on the small example above. Since we are testing with small dataset on Doc, it may remain small. I don't think it will be a big problem if we add it this way.

2023-03-27 18:14 UTC, rasbt commented
Ok perfect, then I'd say it's fine as is because the example is already in the notebook. 

Should be good to merge then, correct?

2023-03-27 18:29 UTC, fatihsen20 commented
> Ok perfect, then I'd say it's fine as is because the example is already in the notebook.
> 
> Should be good to merge then, correct?

Okey sir, please 😊

2023-03-28 22:03 UTC, merged

2023-03-28 22:13 UTC, rasbt commented
Merged it @fatihsen20 . Thanks again for this awesome PR!
 I am hoping to make a new release version on the upcoming weekend